postgres:
  connection_string: postgresql://postgres:pass123@postgis/geodatadb
  auto_publish:
    from_schemas:
      - canarias
pmtiles: 

mbtiles: 
  - /mbtiles/zoran/africa_vtiles_4.mbtiles
# cog: 
sprites:
  sources:
    zorn_sprite: /sprites/zoran
